//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompanyInfo()
        {
            this.CompanyListAppylies = new HashSet<CompanyListAppyly>();
        }
    
        public int ComID { get; set; }
        public string ComPass { get; set; }
        public string ComName { get; set; }
        public Nullable<bool> ComStatus { get; set; }
        public string EmailCom { get; set; }
        public string AboutCom { get; set; }
        public string AddressCom { get; set; }
        public string Phone1Com { get; set; }
        public string Phone2Com { get; set; }
        public string WebsiteCom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyListAppyly> CompanyListAppylies { get; set; }
    }
}
