//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employment
    {
        public int UserID { get; set; }
        public int EmpID { get; set; }
        public string NameEmp { get; set; }
        public string FromEmp { get; set; }
        public string DecripEmp { get; set; }
    
        public virtual InfoUser InfoUser { get; set; }
    }
}
