//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InfoUser()
        {
            this.CompanyListAppylies = new HashSet<CompanyListAppyly>();
            this.Educations = new HashSet<Education>();
            this.Employments = new HashSet<Employment>();
        }
    
        public int USERID { get; set; }
        public string USERNAME { get; set; }
        public string PASS { get; set; }
        public string FULLNAME { get; set; }
        public string ABOUTME { get; set; }
        public Nullable<System.DateTime> BIRTHDAY { get; set; }
        public Nullable<System.DateTime> Datecreate { get; set; }
        public string Livein { get; set; }
        public string Gender { get; set; }
        public string Skill { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyListAppyly> CompanyListAppylies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Education> Educations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employment> Employments { get; set; }
    }
}
