//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.CompanyListAppylies = new HashSet<CompanyListAppyly>();
        }
    
        public int JobID { get; set; }
        public Nullable<int> ComID { get; set; }
        public string JobName { get; set; }
        public string JobDetail { get; set; }
        public Nullable<bool> JobStatus { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<int> JobCatID { get; set; }
        public Nullable<int> PositionID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> SalaryMin { get; set; }
        public Nullable<int> SalaryMax { get; set; }
        public Nullable<System.DateTime> PostDay { get; set; }
        public Nullable<System.DateTime> StartDay { get; set; }
        public Nullable<System.DateTime> EndDay { get; set; }
    
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyListAppyly> CompanyListAppylies { get; set; }
        public virtual JobCatalog JobCatalog { get; set; }
        public virtual Position Position { get; set; }
    }
}
